### ISSUE TITLE
corber build: 'rm' is not recognised in Windows 10

### ISSUE THREAD

**Issue by osawyer** [isleofcode/corber#531] opened 2018-08-23 14:44 UTC
Building Ember app from Windows fails

```
corber build --platform=android --environment=development
corber: Building app
WARNING: corber
config\targets.js has not been configured for platform-optimized corber builds. See http://corber.io/pages/frameworks/ember#configuring-browser-targets for details.
'rm' is not recognized as an internal or external command,
operable program or batch file.
Corber: Command failed: rm -rf corber/cordova/www/*
```

**Comment by osawyer** [comment] 2018-08-24 08:00
Just FYI, I've followed the documentation regarding the warning displayed in the output above.

**Comment by alexblom** [comment] 2018-09-07 17:37
Closing in favor of #530 which we owe you a fix on. There is a more broad windows patch we need to do, and hopefully schedules will be clearing next week :)

**Closed by alexblom** 2018-09-07 17:37 UTC

**Comment by osawyer** [comment] 2018-09-07 19:41
Hi @alexblom, thank you it's great to hear!

**Comment by jl-cs** [comment] 2018-09-13 12:09
Hi there, just wanted to ask if the problem is still on schedule and if there will be a fix soon. Thank you.
