### ISSUE TITLE
'corber start' on ember project targeting Android (Pixel_API_24) fails on Windows 10 

### ISSUE THREAD

**Issue by ChristopherConnock** [isleofcode/corber#652] opened 2020-02-12 16:29 UTC
It looks like corber is looking for:
<ember project>\corber\cordova\platforms\android\build\outputs\apk\debug

when the build directory is actually generated in:
<ember project>\corber\cordova\platforms\android\app\build\outputs\apk\debug

`corber start` leads to the following error:

> events.js:200
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn ls ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
>     at onErrorNT (internal/child_process.js:456:16)
>     at processTicksAndRejections (internal/process/task_queues.js:81:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
>     at onErrorNT (internal/child_process.js:456:16)
>     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn ls',
>   path: 'ls',
>   spawnargs: [
>     '-r',
>     'C:\\Users\\511\\Documents\\GitHub\\roast-ember\\corber\\cordova\\platforms\\android\\build\\outputs\\apk\\debug'
>   ]
> }

**Comment by JordanMcDonough** [comment] 2020-02-18 00:50
Cause of the issue was the spawn of the ls command, you can add my repo as a drop in replacement in the meantime until the issue is resolved: https://github.com/JordanMcDonough/corber

**Comment by alexblom** [comment] 2020-04-17 18:35
Fixed as of 1.4.3. Thank you!

**Closed by alexblom** 2020-04-17 18:35 UTC
